export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const SET_PRODUCTS_SEARCH_QUERY = 'SET_PRODUCTS_SEARCH_QUERY';
export const SHOW_PRODUCT_FORM = 'SHOW_PRODUCT_FORM';
export const CLOSE_PRODUCT_FORM = 'CLOSE_PRODUCT_FORM';
export const CLEAR_PRODUCT_SEARCH_QUERY = 'CLEAR_PRODUCT_SEARCH_QUERY';
export const SET_UPDATED_PRODUCT = 'SET_UPDATED_PRODUCT';