export const GET_WAREHOUSES = 'GET_WAREHOUSES';
export const SET_WAREHOUSES_LOADING = 'SET_WAREHOUSES_LOADING';
export const SET_WAREHOUSES_SEARCH_QUERY = 'SET_WAREHOUSES_SEARCH_QUERY';
export const SHOW_WAREHOUSE_FORM = 'SHOW_WAREHOUSE_FORM';
export const CLOSE_WAREHOUSE_FORM = 'CLOSE_WAREHOUSE_FORM';
export const CLEAR_WAREHOUSE_SEARCH_QUERY = 'CLEAR_WAREHOUSE_SEARCH_QUERY';
export const SET_UPDATED_WAREHOUSE = 'SET_UPDATED_WAREHOUSE';