export const GET_TRANSFERS = 'GET_TRANSFERS';
export const SET_TRANSFERS_LOADING = 'SET_TRANSFERS_LOADING';
export const SET_TRANSFERS_SEARCH_QUERY = 'SET_TRANSFERS_SEARCH_QUERY';
export const SHOW_TRANSFER_FORM = 'SHOW_TRANSFER_FORM';
export const CLOSE_TRANSFER_FORM = 'CLOSE_TRANSFER_FORM';
export const CLEAR_TRANSFER_SEARCH_QUERY = 'CLEAR_TRANSFER_SEARCH_QUERY';
