export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const SET_SUPPLIERS_LOADING = 'SET_SUPPLIERS_LOADING';
export const SET_SUPPLIERS_SEARCH_QUERY = 'SET_SUPPLIERS_SEARCH_QUERY';
export const SHOW_SUPPLIER_FORM = 'SHOW_SUPPLIER_FORM';
export const CLOSE_SUPPLIER_FORM = 'CLOSE_SUPPLIER_FORM';
export const CLEAR_SUPPLIER_SEARCH_QUERY = 'CLEAR_SUPPLIER_SEARCH_QUERY';
export const SET_UPDATED_SUPPLIER = 'SET_UPDATED_SUPPLIER';